# Generated by Django 4.0.1 on 2022-02-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='timelabel',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='history',
            name='new',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], max_length=100),
        ),
        migrations.AlterField(
            model_name='history',
            name='prev',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], max_length=100, null=True),
        ),
    ]
