# Generated by Django 4.0.1 on 2022-02-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='last_emailed',
            field=models.DateTimeField(null=True),
        ),
    ]
