# Generated by Django 4.0.1 on 2022-02-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_rename_timelabel_history_time_alter_history_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='new',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], max_length=100, null=True),
        ),
    ]
